#pragma once
enum class OP_TYPE { OP_ACCEPT, OP_RECV, OP_SEND, OP_SERVER_CONNECT, OP_DISCONNECT, OP_CLIENTMOVE, OP_DUMMYMOVE };

enum class CL_STATE { ST_FREE, ST_ALLOC, ST_LOBBY, ST_MATCHING, ST_INGAME};

enum class ZONE_STATE
{
	FREE = 0,		// 초기화 전
	READY = 1,		// 업데이트 준비, 업데이트 필요없음
	UPDATE = 2,		// 업데이트 필요
};

enum class STORED_PROCEDURE
{
	GET_PLAYER_INFO,
	SAVE_PLAYER_INFO,
	SAVE_TOKEN,
	REGISTER_AUCTION,
	BUY_AUCTION,
	GET_VALIDATOR_IDS,
	STAKE_TOKEN,
	CHANGE_NODE,
	GET_FULL_NODE_INFO,
	GET_STAKED_TOKEN_DATA,
	SIGN_UP,
	GET_AUCTION_INFO,
	GET_AUCTION_PARTS_NUM,
	GET_PLAYER_CUSTOMIZE_PARTS,
	SAVE_SHOP_BUY_INFO,
	GET_PLAYERS_BY_SHOP_TYPE,
};
